### PR TITLE
KAMUDEP-23 | Add optional AWS credentials to Kamu API server

### PR DESCRIPTION
**Pull request by cutwater**

### CODE REVIEW

**Comment by cutwater** [comment]
This is needed for local environment to specify Minio credentials and will be useful for on-prem environments.

**Review by romcheg — CHANGES_REQUESTED** [review]
I think we also need aws_region there.

**Comment by sergiimk** [comment]
I assume this PR is about Minio credentials and we won't be actually using these in AWS environment?

An alternative approach could be using [`extraSecretEnv` pattern](https://github.com/apache/superset/blob/master/helm/superset/values.yaml#L91C8-L91C8). It's very nice to have in general to make charts flexible for experimentation, so perhaps we could just use it for passing credentials to minio as well.

What do you thing @romcheg @cutwater ?

**Review by romcheg — APPROVED** [review]
My concerns have been resolved. LGTM, thanks!

**Review by romcheg — CHANGES_REQUESTED** [review]
Just noticed that the values JSON schema was not updated.

**Review by romcheg — APPROVED** [review]

**Review by sergiimk — APPROVED** [review]

**Pull request merged**
